/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DetectionReviewStep: typeof import('./components/steps/DetectionReviewStep.vue')['default']
    DrawingDialog: typeof import('./components/DrawingDialog.vue')['default']
    DynamicCaptcha: typeof import('./components/DynamicCaptcha.vue')['default']
    ForgotPassword: typeof import('./components/ForgotPassword.vue')['default']
    ImageSelectionStep: typeof import('./components/steps/ImageSelectionStep.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    ResourceDetectionDetailStep: typeof import('./components/steps/ResourceDetectionDetailStep.vue')['default']
    Result: typeof import('./components/result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
    VerificationCodeInput: typeof import('./components/VerificationCodeInput.vue')['default']
  }
}
