/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/annual': RouteRecordInfo<'/annual', '/annual', Record<never, never>, Record<never, never>>,
    '/history': RouteRecordInfo<'/history', '/history', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/Profile': RouteRecordInfo<'/Profile', '/Profile', Record<never, never>, Record<never, never>>,
    '/review': RouteRecordInfo<'/review', '/review', Record<never, never>, Record<never, never>>,
    '/step/[id]': RouteRecordInfo<'/step/[id]', '/step/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/task/[review_request_id]': RouteRecordInfo<'/task/[review_request_id]', '/task/:review_request_id', { review_request_id: ParamValue<true> }, { review_request_id: ParamValue<false> }>,
    '/task/detail/[manual_review_id]': RouteRecordInfo<'/task/detail/[manual_review_id]', '/task/detail/:manual_review_id', { manual_review_id: ParamValue<true> }, { manual_review_id: ParamValue<false> }>,
    '/upload': RouteRecordInfo<'/upload', '/upload', Record<never, never>, Record<never, never>>,
  }
}
