# Generated by Django 5.2.13 on 2026-04-19 17:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver_id", models.CharField(max_length=100)),
                ("receiver_name", models.CharField(max_length=100)),
                ("sender_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sender_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[(1, "GLOBAL"), (2, "SYSTEM"), (3, "P2R"), (4, "R2P")]
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("read", "已读"), ("unread", "未读")],
                        default="unread",
                        max_length=10,
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "notification",
                "ordering": ["-notified_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("publisher", "Publisher"),
                            ("reviewer", "Reviewer"),
                        ],
                        default="publisher",
                        max_length=50,
                    ),
                ),
                ("permission", models.IntegerField(null=True)),
                ("profile", models.TextField(blank=True, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="avatars/default.png",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                ("reset_code", models.CharField(blank=True, max_length=6, null=True)),
                ("reset_code_expiry", models.DateTimeField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("remaining_non_llm_uses", models.PositiveIntegerField(default=100)),
                ("remaining_llm_uses", models.PositiveIntegerField(default=3)),
                ("last_reset_time", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="FileManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("file_type", models.CharField(max_length=50)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("paper", "Paper"),
                            ("review_paper", "ReviewPaper"),
                            ("review_file", "ReviewFile"),
                        ],
                        db_index=True,
                        default="image",
                        max_length=20,
                    ),
                ),
                (
                    "stored_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "upload_time",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("Biology", "Biology"),
                            ("Medicine", "Medicine"),
                            ("Chemistry", "Chemistry"),
                            ("Graphics", "Graphics"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                    ),
                ),
                (
                    "linked_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_children",
                        to="core.filemanagement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetectionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("paper", "Paper"),
                            ("review", "Review"),
                        ],
                        db_index=True,
                        default="image",
                        max_length=20,
                    ),
                ),
                ("task_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ("completion_time", models.DateTimeField(blank=True, null=True)),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        help_text="生成的 PDF 检测报告",
                        null=True,
                        upload_to="reports/",
                    ),
                ),
                ("cmd_block_size", models.IntegerField(blank=True, null=True)),
                ("urn_k", models.FloatField(blank=True, null=True)),
                ("if_use_llm", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="detection_tasks",
                        to="core.filemanagement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="extracted_images/")),
                ("extracted_from_pdf", models.BooleanField(default=False)),
                ("page_number", models.IntegerField(blank=True, null=True)),
                (
                    "upload_time",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ("isDetect", models.BooleanField(default=False)),
                ("isReview", models.BooleanField(default=False)),
                ("isFake", models.BooleanField(default=False)),
                (
                    "detection_task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_uploads",
                        to="core.detectiontask",
                    ),
                ),
                (
                    "file_management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_uploads",
                        to="core.filemanagement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score1", models.IntegerField(blank=True, null=True)),
                ("score2", models.IntegerField(blank=True, null=True)),
                ("score3", models.IntegerField(blank=True, null=True)),
                ("score4", models.IntegerField(blank=True, null=True)),
                ("score5", models.IntegerField(blank=True, null=True)),
                ("score6", models.IntegerField(blank=True, null=True)),
                ("score7", models.IntegerField(blank=True, null=True)),
                ("reason1", models.TextField(blank=True, null=True)),
                ("reason2", models.TextField(blank=True, null=True)),
                ("reason3", models.TextField(blank=True, null=True)),
                ("reason4", models.TextField(blank=True, null=True)),
                ("reason5", models.TextField(blank=True, null=True)),
                ("reason6", models.TextField(blank=True, null=True)),
                ("reason7", models.TextField(blank=True, null=True)),
                ("points1", models.JSONField(blank=True, null=True)),
                ("points2", models.JSONField(blank=True, null=True)),
                ("points3", models.JSONField(blank=True, null=True)),
                ("points4", models.JSONField(blank=True, null=True)),
                ("points5", models.JSONField(blank=True, null=True)),
                ("points6", models.JSONField(blank=True, null=True)),
                ("points7", models.JSONField(blank=True, null=True)),
                ("result", models.BooleanField(null=True)),
                (
                    "review_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.localtime
                    ),
                ),
                (
                    "img",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_reviews",
                        to="core.imageupload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_fake", models.BooleanField(null=True)),
                ("confidence_score", models.FloatField(null=True)),
                ("detection_time", models.DateTimeField(blank=True, null=True)),
                ("is_under_review", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "正在检测中"),
                            ("completed", "检测已完成"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "llm_judgment",
                    models.TextField(
                        blank=True, help_text="大语言模型生成的文字判断结果", null=True
                    ),
                ),
                (
                    "ela_image",
                    models.ImageField(
                        blank=True,
                        help_text="ELA 算法产生的可视化图像",
                        null=True,
                        upload_to="ela_results/",
                    ),
                ),
                (
                    "llm_image",
                    models.ImageField(
                        blank=True,
                        help_text="LLM 产生的可视化图像",
                        null=True,
                        upload_to="llm_results/",
                    ),
                ),
                (
                    "exif_photoshop",
                    models.BooleanField(
                        help_text="EXIF 判定：是否用 Photoshop 修改", null=True
                    ),
                ),
                (
                    "exif_time_modified",
                    models.BooleanField(
                        help_text="EXIF 判定：是否修改拍摄 / 创建时间", null=True
                    ),
                ),
                (
                    "detection_task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_results",
                        to="core.detectiontask",
                    ),
                ),
                (
                    "image_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_results",
                        to="core.imageupload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_time",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("detection", "Detection"),
                            ("review_request", "Review Request"),
                            ("manual_review", "Manual Review"),
                        ],
                        max_length=50,
                    ),
                ),
                ("related_model", models.CharField(max_length=50)),
                ("related_id", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManualReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("undo", "Undo"), ("completed", "Completed")],
                        default="undo",
                        max_length=50,
                    ),
                ),
                (
                    "review_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.localtime
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        help_text="生成的 PDF 检测报告",
                        null=True,
                        upload_to="reports/",
                    ),
                ),
                (
                    "img_reviews",
                    models.ManyToManyField(
                        related_name="manual_reviews", to="core.imagereview"
                    ),
                ),
                (
                    "imgs",
                    models.ManyToManyField(
                        related_name="manual_reviews", to="core.imageupload"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="imagereview",
            name="manual_review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_reviews",
                to="core.manualreview",
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_like", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "feedback_time",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manual_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="core.manualreview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organization_logos/"
                    ),
                ),
                (
                    "proof_materials",
                    models.FileField(
                        blank=True, null=True, upload_to="proof_materials/"
                    ),
                ),
                ("remaining_non_llm_uses", models.PositiveIntegerField(default=100)),
                ("remaining_llm_uses", models.PositiveIntegerField(default=3)),
                ("last_reset_time", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_organization",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="manualreview",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.CreateModel(
            name="InvitationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("publisher", "Publisher"), ("reviewer", "Reviewer")],
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="filemanagement",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="detectiontask",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("admin_username", models.CharField(max_length=150)),
                ("admin_email", models.EmailField(max_length=254)),
                ("admin_password", models.CharField(max_length=128)),
                (
                    "proof_materials",
                    models.FileField(
                        blank=True, null=True, upload_to="proof_materials/"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organization_logos/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublisherReviewerRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        limit_choices_to={"role": "publisher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        limit_choices_to={"role": "reviewer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("publisher", "reviewer")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="related_reviewers",
            field=models.ManyToManyField(
                limit_choices_to={"role": "reviewer"},
                related_name="related_publishers",
                through="core.PublisherReviewerRelationship",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ReviewRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.localtime
                    ),
                ),
                (
                    "status1",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField()),
                ("review_start_time", models.DateTimeField(blank=True, null=True)),
                ("review_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status2",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("refused", "Refused"),
                            ("accepted", "Accepted"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("check_reason", models.TextField()),
                (
                    "detection_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_requests",
                        to="core.detectionresult",
                    ),
                ),
                (
                    "imgs",
                    models.ManyToManyField(
                        related_name="review_requests", to="core.imageupload"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "reviewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="review_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="manualreview",
            name="review_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_reviews",
                to="core.reviewrequest",
            ),
        ),
        migrations.AddField(
            model_name="detectionresult",
            name="review_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.reviewrequest",
            ),
        ),
        migrations.CreateModel(
            name="SubDetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("method1", "Method-1"),
                            ("method2", "Method-2"),
                            ("method3", "Method-3"),
                            ("method4", "Method-4"),
                            ("method5", "Method-5"),
                            ("method6", "Method-6"),
                            ("method7", "Method-7"),
                        ],
                        max_length=30,
                    ),
                ),
                ("probability", models.FloatField()),
                (
                    "mask_image",
                    models.ImageField(blank=True, null=True, upload_to="masks/"),
                ),
                ("mask_matrix", models.JSONField()),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.localtime),
                ),
                (
                    "detection_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_results",
                        to="core.detectionresult",
                    ),
                ),
            ],
            options={
                "unique_together": {("detection_result", "method")},
            },
        ),
    ]
